### ISSUE TITLE
Properly process files uploaded as multipart form data

### ISSUE THREAD

**Issue by mauricerenck** [sebastiangreger/kirby3-micropublisher#8]
Hey,

I am trying around to use different templates for a simple note or an image post. I tried different variations but couldn't get it working with 

```
'identify' => [
                'unique' => null,
                'has' => ['photo', 'files.photo', 'files[photo]'],
                'hasnot' => null,
            ],
```

(I always used on of the strings in 'has' not all together)

Is it possible to identify posts by existing files?

I also tried to write a file to a field:

```
            'files' => [
                'photo' => ['image', true, 'hero'],
            ],
```

The image is uploaded, the note created, but there is no `hero` in the markdown. I am using micropub.rocks for testing.

**Comment by sebastiangreger** [comment]
Hi! Based on a quick look, this indeed does not seem to work when the image is submitted as a multipart POST request (which actually is the more common way; it only works when the app uploads the image separately and submits its URL as a `photo` field on form submission).

So I am sorry to say: right now I don't see a way to check for "has photo" in the `identify` routine :disappointed: This being a super-relevant use case, I should try to look into this at some point. For the time being, one workaround idea comes to mind:

You could check the log file `site/logs/micropublisher/micropub.log` on a successful Micropub submission with an image to see whether your Micropub app submits an alt text; an extension of the core Micropub spec. Not sure does micropub.rocks send that field, but I am using the Indigenous app and it submits an array field named `mp-photo-alt` (with an optional alt text, but it's present nonetheless) whenever I upload a photo. That field name should be possible to check for in a `has` rule (I haven't tried, though).

Unfortunately, I don't have an instant hack at hand to solve the `hero` field issue – it seems to be the same underlying issue with the multipart form data coming from the Micropub app. Only thing that comes to mind as a hotfix is a `post.create:after` hook to deal with this.

**Comment by mauricerenck** [comment]
Hey Sebastian,

thank you for the feedback.

I found a solution for my case at least. I already use a single template for all my post types and then different snippets to render every post type a bit different. This way I also can check if the post type is a `note` or if it's a `note` and `->hasImages()`. In both cases I can use different snippets. Maybe this is helpful for others running into the same issue.

Maybe I can spend some time playing around with this issue (after getting my own plugins to work with K3.6  😅 )

**Comment by sebastiangreger** [comment]
Moin Maurice,

Thanks for pointing out these issues! I took the opportunity to fix a long-standing incompatibility with the (living) Indieauth spec and looked into these file-related shortcomings at the same time.

Today's [v1.0-beta.4](https://github.com/sebastiangreger/kirby3-micropublisher/releases/tag/v1.0-beta.4) supports `has`/`hasnot` rules for file types (`photo`, `audio`, `video`) – I tested it with Quill – and the second issue indeed was a bug: now you can set `'photo' => ['image', true, 'hero']` and one or multiple file(s) submitted as `photo` is/are stored using the file blueprint `image` **plus** the first one added to the file field `hero`.

Hope this all works now.

Oh my, 3.6… that's indeed a bunch of work on the horizon, it seems :scream: Good luck with that!
